# yaml-language-server: $schema=https://www.schemastore.org/any.json

name: day01
version: 0.1.0.0
github: "eatobin/day01"
license: BSD-3-Clause
author: "Eric Tobin"
maintainer: "eatobin@gmail.com"
copyright: "None"

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            None

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/eatobin/day01#readme>

dependencies:
  - base >= 4.7 && < 5
  - hspec

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  day01-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - day01
    when:
      - condition: false
        other-modules: Paths_day01

tests:
  day01-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - day01
